<?php
/**
 * Created by PhpStorm.
 * User: sa
 * Date: 2017/10/27
 * Time: 19:00
 * 用户模型
 */
namespace app\model;

use core\Model;

class User extends Model
{
    public function getTableName()
    {
        //parent::getTableName(); // TODO: Change the autogenerated stub
        return 'user';
    }
}